FROM golang:1.22-alpine

WORKDIR /app

# Install air for hot reload
RUN go install github.com/cosmtrek/air@latest

# Install dependencies
RUN apk add --no-cache git

EXPOSE 8081 50051

CMD ["air", "-c", ".air.toml"]