global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector exported metrics
  - job_name: 'crypto-tracker-metrics'
    static_configs:
      - targets: ['crypto-tracker-otel-collector:8889']
    scrape_interval: 10s